/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * ThinkEasy
 * Test Task BE
 * OpenAPI spec version: 1.0
 */

export interface PostResponse {
  id: string;
  createdAt: string;
  updatedAt: string;
  title: string;
  content: string;
  published: boolean;
  authorId: string;
}
