/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * ThinkEasy
 * Test Task BE
 * OpenAPI spec version: 1.0
 */

export interface SignupInput {
  email: string;
  password: string;
  firstname: string;
  lastname: string;
}
